In [101]:
import pandas as pd
import numpy as np

from sklearn import utils
import torch
import torch.nn.functional as F

# Preparing Dataset

In [102]:
# laod filtered data
features = np.load('features_f.npy', allow_pickle=True)
labels = np.load('labels_f.npy', allow_pickle=True)

In [103]:
# convert features to array
features = features.transpose()
features

array([['Chad Hurley', 'Gwyneth Paltrow', 'Jason Calacanis', ...,
        'Gene Wang', 'Sasan Amini', 'Mike Hurst'],
       ['YouTube', 'Goop Inc.', 'Inside.com', ..., 'People Power',
        'Clear Labs', 'Exactuals'],
       [0.0, 0.0, 3.0, ..., 1.0, 0.0, 0.0],
       ...,
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=object)

In [104]:
# skiping first values as in the guide
np_ftrs = features[1:]
np_ftrs

array([['YouTube', 'Goop Inc.', 'Inside.com', ..., 'People Power',
        'Clear Labs', 'Exactuals'],
       [0.0, 0.0, 3.0, ..., 1.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=object)

In [105]:
len(np_ftrs)

8

In [144]:
# filter values that are not integers
for idx,data in enumerate(np_ftrs[3]):
    if type(data)!= int:
        print(data)
        np_ftrs[3][idx]= 'nan'
np_ftrs

In [145]:
# convert strings to numbers
for idx, data in enumerate(np_ftrs):
    np_ftrs[idx]=np.unique(np_ftrs[idx], return_inverse=True)[1]
    print(np_ftrs[idx])

[0 1 1 1 3 0 1 2 0 1 2 0 0 1 1 1 0 2 0 0 3 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 1 1 0 1 1 0 1 2 0 0 0 0 1 2 2 1 0 2 2 3 0 0 0 1 0 1 0 1 0
 1 1 2 1 2 1 1 0 0 1 1 3 1 0 1 0 2 2 1 1 0 1 0 1 1 1 2 0 1 1 0 1 0 0 1 0 1
 0 1 1 2 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 2 1 1 0 0 2 0 0 1 0 0 1 0 0 1 0
 1 0 0 1 0 1 0 0 1 2 1 0 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 1 0 1 0 0 2 4 2 0
 0 2 0 0 0 2 1 1 0 0 0 1 1 0 0 0 1 1 0 1 0 2 0 2 0 1 0 2 0 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 1
 1 0 2 0 2 2 3 0 0 0 2 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 2 0 1 0 0 1 0 0 0 0 0
 0 0 2 0 1 1 2 1 0 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 1 1 1 0 0 1 0 0 0 2 2 0 0 1 0 1 0 0 1 0 2 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1
 1 1 0 0 0 1 1 0 0 1 1 0 0 2 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0
 0 1 0 1 2 1 0 0 0 0 0 1 1 2 0 1 1 0 0 0 0 0 0 1 1 1 0 1 0 1 1 3 1 2 0 0 3
 1 0 1 1 1 0 2 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1 0 1 0 1 1 2 1 0 0 1 1 0
 0 0 0 1 1 0 1 0 0 0 1 0 

In [146]:
# converting nan to numbers
for i in range(len(np_ftrs)):
    try:
        np_ftrs[i] = np_ftrs[i].astype(int)
    except:
        for idx, ele in enumerate(np_ftrs[i]):
            if ele!= 0.0 and ele!= 1.0:
                np_ftrs[i][idx] = 0.0
        np_ftrs[i] = np_ftrs[i].astype(int)
    

In [147]:
# swiching to np featues
np_ftrs = np_ftrs[1:]
np_ftrs = np_ftrs.transpose()
np_ftrs

array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 2, 0, 0],
       ...,
       [0, 0, 0, 2, 1, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 2, 0, 0]], dtype=object)

In [148]:
df = pd.DataFrame(np_ftrs)
print(df)
# checking what we got  after swiching to np features

     0  1  2  3  4  5
0    0  0  0  1  0  0
1    0  0  0  2  0  0
2    0  0  0  2  0  0
3    0  0  0  2  0  0
4    0  0  1  2  0  0
..  .. .. .. .. .. ..
802  0  0  3  2  0  1
803  0  0  0  1  0  0
804  0  0  0  2  1  0
805  0  0  1  0  0  0
806  0  0  1  2  0  0

[807 rows x 6 columns]


In [149]:
tr_ftrs = F.normalize(torch.FloatTensor(list(np_ftrs)))

In [150]:
tr_ftrs

tensor([[0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000, 0.8944, 0.4472, 0.0000],
        [0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.4472, 0.8944, 0.0000, 0.0000]])

In [151]:
lbls = labels.transpose()
lbls.shape

(6, 808)

In [152]:
lbls[5]

array([1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0,
       0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0,
       0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0,
       0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0,
       0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.

In [153]:
lbl_v = lbls[5]

In [154]:
lbl_v

array([1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0,
       0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0,
       0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0,
       0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0,
       0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.

In [155]:
lbls[4]

array(['88,400,000.00', '65,000,000.00', '0', '288,120,000.00',
       '238,590,000.00', '0', '500,000,000.00', '173,970,000.00',
       '310,000,000.00', '1,630,000,000.00', '0', '35,540,000.00',
       '80,350,000.00', '225,000,000.00', '414,500,000.00',
       '287,440,000.00', '254,100,000.00', '105,000,000.00',
       '61,020,000.00', '100,000,000.00', '316,000,000.00',
       '53,800,000.00', '0', '57,380,000.00', '140,000,000.00',
       '55,500,000.00', '250,000,000.00', '150,000,000.00',
       '87,000,000.00', '468,000,000.00', '77,430,000.00',
       '600,000,000.00', '154,910,000.00', '150,000,000.00',
       '192,110,000.00', '800,000,000.00', '555,000,000.00',
       '235,000,000.00', '200,000,000.00', '68,000,000.00',
       '61,190,000.00', '1,000,000,000.00', '66,900,000.00',
       '130,000,000.00', '31,400,000.00', '275,000,000.00',
       '42,300,000.00', '160,000,000.00', '120,000,000.00',
       '160,000,000.00', '56,490,000.00', '0', '71,000,000.00',
       '560,

In [156]:
lbl_av = lbls[3]
lbl_bv = lbls[4]

In [ ]:
# setting sucsess and failure values
for idx, data in enumerate(lbl_v):
    if data == '#VALUE!':
        try:
            temp = float(lbl_bv[idx].replace(',',''))/ float(lbl_av[idx].replace(',',''))
            if temp>float(0):
                lbl_v[idx] = float(1)
            else:
                lbl_v[idx]= float(0)
        except:
            lbl_v[idx] = float(0)
    elif data == '#DIV/0!':
        try:
            temp = float(lbl_bv[idx].replace(',',''))/ float(lbl_av[idx].replace(',',''))
            if temp>float(0):
                lbl_v[idx] = float(1)
            else:
                lbl_v[idx] = float(0)
        except:
            lbl_v[idx] = float(0)
    elif float(data.replace(',','')) > float(0):
        lbl_v[idx] = float(1)
    else:
        lbl_v[idx] = float(0)
        

lbl_v = lbl_v.astype(float)

In [ ]:
tr_lbl = torch.LongTensor(lbl_v)
# changing the values to long tensor to work with the model

In [ ]:
tr_lbl

tensor([1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,

In [ ]:
#shuffle
tr_ftrs, tr_lbl= utils.shuffle(tr_ftrs, tr_lbl)

In [ ]:
print(len(tr_ftrs), len(tr_lbl))

808 808


In [ ]:
# split data to train test
train_ftrs = tr_ftrs[0:646]
train_lbl = tr_lbl[0:646]

test_ftrs = tr_ftrs[646:808]
test_lbl = tr_lbl[646:808]

print(len(train_ftrs), len(test_ftrs))

646 162


In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression


# Create and fit the linear regression model
model = LinearRegression()
model.fit(train_ftrs, train_lbl)

# Print the coefficients and intercept
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

# Predict on new data
predictions = model.predict(test_ftrs)
print("Predictions:", predictions)


Coefficients: [-1.2232767e-01  1.3976172e-01 -2.9802322e-08  1.5579376e-01
  2.1640792e-01  1.5589434e-01  5.3883981e-02]
Intercept: 0.2607606
Predictions: [0.41975284 0.4410383  0.5085171  0.39961514 0.4723544  0.55275935
 0.2607606  0.5273632  0.13843293 0.52459186 0.50460434 0.5273632
 0.32253367 0.2607606  0.47716853 0.13843293 0.4410383  0.5273632
 0.49819553 0.44897562 0.523759   0.37444222 0.47716853 0.2607606
 0.31464458 0.4849835  0.39961514 0.4784194  0.3272854  0.47831863
 0.47716853 0.2607606  0.52648413 0.21236362 0.39961514 0.51043034
 0.39961514 0.42643338 0.5495955  0.51546156 0.3970781  0.44865963
 0.52648413 0.52065426 0.39961514 0.4342057  0.370068   0.47716853
 0.47716853 0.51043034 0.52940935 0.3272854  0.5085171  0.28449583
 0.39961514 0.5387013  0.2607606  0.47716853 0.13843293 0.27308834
 0.13843293 0.39961514 0.4837759  0.44897562 0.40913025 0.4410383
 0.54628456 0.47716853 0.3377673  0.41655436 0.28442472 0.50626636
 0.50460434 0.4095149  0.46006772 0.42797387

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Create and fit the linear regression model
model = LinearRegression()
model.fit(train_ftrs, train_lbl)

# Predict on the test set
predictions = model.predict(test_ftrs)

# Calculate evaluation metrics
mae = mean_absolute_error(test_lbl, predictions)
mse = mean_squared_error(test_lbl, predictions)
rmse = np.sqrt(mse)

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)


Mean Absolute Error (MAE): 0.45719275687947686
Mean Squared Error (MSE): 0.22354472229411892
Root Mean Squared Error (RMSE): 0.4728051631424079


In [ ]:
from sklearn.metrics import accuracy_score

# Assuming you have already trained the model and obtained predictions
predicted_labels = model.predict(test_ftrs)  # Predicted labels for the test set

# Convert predicted probabilities to binary labels (if needed)
predicted_labels = (predicted_labels > 0.5).astype(int)

# Calculate accuracy
accuracy = accuracy_score(test_lbl, predicted_labels)

print("Accuracy:", accuracy)


Accuracy: 0.6481481481481481


In [ ]:
from sklearn.linear_model import Ridge, Lasso

# Create and fit the Ridge regression model
ridge_model = Ridge(alpha=0.5)  # alpha is the regularization strength
ridge_model.fit(train_ftrs, train_lbl)

# Create and fit the Lasso regression model
lasso_model = Lasso(alpha=0.5)  # alpha is the regularization strength
lasso_model.fit(train_ftrs, train_lbl)

# Predict on the test set using Ridge and Lasso models
ridge_predictions = ridge_model.predict(test_ftrs)
lasso_predictions = lasso_model.predict(test_ftrs)

# Calculate accuracy or other evaluation metrics for Ridge and Lasso predictions
ridge_accuracy = accuracy_score(test_lbl, (ridge_predictions > 0.5).astype(int))
lasso_accuracy = accuracy_score(test_lbl, (lasso_predictions > 0.5).astype(int))

print("Ridge Accuracy:", ridge_accuracy)
print("Lasso Accuracy:", lasso_accuracy)


Ridge Accuracy: 0.6481481481481481
Lasso Accuracy: 0.6111111111111112


In [ ]:
from sklearn.linear_model import ElasticNet

# Create and fit the Elastic Net model
elastic_net_model = ElasticNet(alpha=0.5, l1_ratio=0.5)  # alpha and l1_ratio are regularization parameters
elastic_net_model.fit(train_ftrs, train_lbl)

# Predict on the test set using the Elastic Net model
elastic_net_predictions = elastic_net_model.predict(test_ftrs)

# Calculate accuracy or other evaluation metrics for Elastic Net predictions
elastic_net_accuracy = accuracy_score(test_lbl, (elastic_net_predictions > 0.5).astype(int))

print("Elastic Net Accuracy:", elastic_net_accuracy)


Elastic Net Accuracy: 0.6111111111111112
